# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0003_auto_20170122_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cert',
            name='product',
        ),
        migrations.AddField(
            model_name='cert',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='certificatons',
            field=models.ManyToManyField(to='thesite.Cert'),
        ),
    ]
