# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0004_auto_20170122_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='certificatons',
            field=models.ManyToManyField(blank=True, to='thesite.Cert'),
        ),
        migrations.AlterField(
            model_name='product',
            name='conglomerate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='thesite.Conglomerate'),
        ),
    ]
