# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0006_auto_20170122_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='certificatons',
            field=models.ManyToManyField(blank=True, to='thesite.Cert'),
        ),
    ]
