# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-10 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0007_auto_20170122_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved_edit',
            field=models.BooleanField(default=False),
        ),
    ]
