# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-10 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0008_product_approved_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='conglomerate',
            name='approved_edit',
            field=models.BooleanField(default=False),
        ),
    ]
