# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-11 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0010_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verification',
            name='date',
            field=models.DateField(default=datetime.date(2017, 2, 11)),
        ),
        migrations.AddField(
            model_name='verification',
            name='individual',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='verification',
            name='who',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
