# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-11 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0011_auto_20170211_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='conglomerate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='thesite.Conglomerate'),
        ),
    ]
