# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-11 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0012_verification_conglomerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='conglomerate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesite.Conglomerate'),
        ),
    ]
