# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-11 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0014_remove_verification_conglomerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='conglomerate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thesite.Conglomerate'),
        ),
    ]
