# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0017_auto_20170211_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='verification',
            name='comment_employ',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='verification',
            name='comment_sustain',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
