# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-11 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0018_auto_20170211_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='comment',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='comment_employ',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='comment_sustain',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='individual',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thesite.Product'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='who',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
