# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-12 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0019_auto_20170211_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conglomerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='verification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
