# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-18 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0020_auto_20170212_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conglomerate',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='verification',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
