# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-18 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0022_auto_20170218_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conglomerate',
            options={'ordering': ('name', '-last_updated')},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', '-last_updated')},
        ),
    ]
